package app.admin;
// Generated Nov 9, 2014 3:32:25 AM by Hibernate Tools 3.2.1.GA



/**
 * MailingListVendor generated by hbm2java
 */
public class MailingListVendor  implements java.io.Serializable {


     private Integer memberId;
     private Integer mailId;
     private String vendorId;

    public MailingListVendor() {
    }

    public MailingListVendor(Integer mailId, String vendorId) {
       this.mailId = mailId;
       this.vendorId = vendorId;
    }
   
    public Integer getMemberId() {
        return this.memberId;
    }
    
    public void setMemberId(Integer memberId) {
        this.memberId = memberId;
    }
    public Integer getMailId() {
        return this.mailId;
    }
    
    public void setMailId(Integer mailId) {
        this.mailId = mailId;
    }

  public String getVendorId() {
    return vendorId;
  }

  public void setVendorId(String vendorId) {
    this.vendorId = vendorId;
  }

    




}


