package app.admin;
// Generated Nov 9, 2014 10:26:30 AM by Hibernate Tools 3.2.1.GA



/**
 * MailingList generated by hbm2java
 */
public class MailingList  implements java.io.Serializable {


     private Integer mailid;
     private String mailName;
     private String mailType;
     private String mailCategory;
     private String filter1;
     private String filter2;
     private String filter3;
     private String filter4;
     private String filter5;
     private String filter6;
     private String filter7;
     private String filter8;
     private String filter9;
     private String filter10;
     private String filter11;
     private String filter12;
     
     

    public MailingList() {
    }

    public MailingList(String mailName, String mailType, String mailCategory) {
       this.mailName = mailName;
       this.mailType = mailType;
       this.mailCategory = mailCategory;
    }
   
    public Integer getMailid() {
        return this.mailid;
    }
    
    public void setMailid(Integer mailid) {
        this.mailid = mailid;
    }
    public String getMailName() {
        return this.mailName;
    }
    
    public void setMailName(String mailName) {
        this.mailName = mailName;
    }
    public String getMailType() {
        return this.mailType;
    }
    
    public void setMailType(String mailType) {
        this.mailType = mailType;
    }
    public String getMailCategory() {
        return this.mailCategory;
    }
    
    public void setMailCategory(String mailCategory) {
        this.mailCategory = mailCategory;
    }

    public String getFilter1() {
        return filter1;
    }

    public void setFilter1(String filter1) {
        this.filter1 = filter1;
    }

    public String getFilter2() {
        return filter2;
    }

    public void setFilter2(String filter2) {
        this.filter2 = filter2;
    }

    public String getFilter3() {
        return filter3;
    }

    public void setFilter3(String filter3) {
        this.filter3 = filter3;
    }

    public String getFilter4() {
        return filter4;
    }

    public void setFilter4(String filter4) {
        this.filter4 = filter4;
    }

    public String getFilter5() {
        return filter5;
    }

    public void setFilter5(String filter5) {
        this.filter5 = filter5;
    }

    public String getFilter6() {
        return filter6;
    }

    public void setFilter6(String filter6) {
        this.filter6 = filter6;
    }

    public String getFilter7() {
        return filter7;
    }

    public void setFilter7(String filter7) {
        this.filter7 = filter7;
    }

    public String getFilter8() {
        return filter8;
    }

    public void setFilter8(String filter8) {
        this.filter8 = filter8;
    }

    public String getFilter9() {
        return filter9;
    }

    public void setFilter9(String filter9) {
        this.filter9 = filter9;
    }

    public String getFilter10() {
        return filter10;
    }

    public void setFilter10(String filter10) {
        this.filter10 = filter10;
    }

    public String getFilter11() {
        return filter11;
    }

    public void setFilter11(String filter11) {
        this.filter11 = filter11;
    }

    public String getFilter12() {
        return filter12;
    }

    public void setFilter12(String filter12) {
        this.filter12 = filter12;
    }

 



}


