//ClientSearchForm.java works to collect/display values
//to/from the web pages (jsp) related to a search on clients

package app.client;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionError;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;

public class ClientSearchForm extends ActionForm
{
	private String companyName;
        private String clientContactFirstName;
	private String clientContactLastName;
        private String status;
        private String clientLocation;
        private String clientPhoneNo;
        private String clientIndustry;
        private String clientAe;
        
	/**
	* validate() ensures the user's item is valid and returns the appropriate <code>ActionErrors</code>
	* object, if any errors are generated.
	* 
	* @return <code>ActionErrors</code> A collection of errors generated by validation process.
	* 
	 */
	public ActionErrors validate(
		ActionMapping mapping,
		HttpServletRequest request)
	{
		/*
		 * Create new ActionErrors object to hold any errors we discover
		 * upon validation of the form's fields.
		 * 
		 */
		ActionErrors errors = new ActionErrors();

		/*
		 * Check the name field to ensure that it is neither empty nor
		 * contains a zero length string.
		 * 
		 */
		if (companyName == null || companyName.length() < 1)
		{
			errors.add("Comapny_name", new ActionMessage("errors.required", "Company Name"));
			//errors.add("name", new ActionError("errors.required", "Name"));

		}
                if (clientContactLastName == null || clientContactLastName.length() < 1)
		{
			
			//errors.add("name", new ActionError("errors.required", "Name"));

		}

		return errors;
	}

	/**
	 * Clears the object prior to each request. 
	 * 
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request)
	{
		this.clear();
	}

	public String getStatus()
	{
		return this.status;
	}

        
	public String getCompanyName()
	{
		return this.companyName;
	}

	
	public String getClientContactLastName()
	{
		return this.clientContactLastName;
	}
        
        public String getClientContactFirstName()
	{
		return this.clientContactFirstName;
	}

	public void setStatus(String s)
	{
		this.status = s;
	}
        
	public void setCompanyName(String n)
	{
		this.companyName = n;
	}

	
	public void setClientContactLastName(String n)
	{
		this.clientContactLastName = n;
	}
        
        public void setClientContactFirstName(String n)
	{
		this.clientContactFirstName = n;
	}

 

    public String getClientLocation() {
        return this.clientLocation;
    }

    public void setClientLocation(String n) {
        this.clientLocation = n;
    }

    public String getClientPhoneNo() {
        return this.clientPhoneNo;
    }

    public void setClientPhoneNo(String n) {
        this.clientPhoneNo = n;
    }

    public String getClientIndustry() {
        return clientIndustry;
    }

    public void setClientIndustry(String clientIndustry) {
        this.clientIndustry = clientIndustry;
    }

    public String getClientAe() {
        return clientAe;
    }

    public void setClientAe(String clientAe) {
        this.clientAe = clientAe;
    }

 

	/**
	 *
	 * clear() sets all the object's fields to <code>null</code>.
	 *
	 */
	public void clear()
	{
                this.status = null;
		this.companyName = null;
		this.clientContactLastName = null;
                this.clientContactFirstName = null;
                this.clientLocation=null;
                this.clientPhoneNo=null;
                this.clientAe=null;
                this.clientIndustry=null;

	}

}
